# Limiting the CRs that Argo is allowed to view and create
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: clusters-app-project
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: 'cluster.open-cluster-management.io'
    kind: ManagedCluster
  - group: ''
    kind: Namespace
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Namespace
  - group: ''
    kind: Secret
  - group: 'agent-install.openshift.io'
    kind: InfraEnv
  - group: 'agent-install.openshift.io'
    kind: NMStateConfig
  - group: 'extensions.hive.openshift.io'
    kind: AgentClusterInstall
  - group: 'hive.openshift.io'
    kind: ClusterDeployment
  - group: 'metal3.io'
    kind: BareMetalHost
  - group: 'agent.open-cluster-management.io'
    kind: KlusterletAddonConfig
  - group: 'cluster.open-cluster-management.io'
    kind: ManagedCluster
  - group: 'ran.openshift.io'
    kind: SiteConfig
  - group: 'batch'
    kind: Job
  - group: 'rbac.authorization.k8s.io'
    kind: Role
  - group: 'rbac.authorization.k8s.io'
    kind: RoleBinding
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  - group: ''
    kind: Pod
  - group: ''
    kind: ServiceAccount
  - group: 'action.open-cluster-management.io'
    kind: ManagedClusterAction
  - group: 'view.open-cluster-management.io'
    kind: ManagedClusterView
  # allow usage of SealedSecrets
  - group: 'bitnami.com'
    kind: SealedSecret
  # allow usage of AnsibleJob and AnsibleWorkflow
  - group: 'tower.ansible.com'
    kind: AnsibleJob
  - group: 'tower.ansible.com'
    kind: AnsibleWorkflow
  # Vault config operator
  - group: 'redhatcop.redhat.io'
    kind: VaultSecret
  sourceRepos:
  - '*'